name: Bundle and Release OpenAPI

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Update OpenAPI version
        run: |
          # タグ名から 'v' を除いた数値を取得 (例: v1.2.3 -> 1.2.3)
          NEW_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          # バンドルされたファイル内のバージョンを更新
          yq -i ".info.version = \"$NEW_VERSION\"" main.yaml

      - name: Bundle OpenAPI
        run: |
          npx @redocly/cli bundle main.yaml --output spec/openapi.yaml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bundle and update version to ${{ github.ref_name }}"
          file_pattern: "spec/openapi.yaml"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: spec/openapi.yaml # リリースに成果物を添付する場合
          generate_release_notes: true
